import type { Metadata } from "next";
import { Montagu_Slab } from "next/font/google";
import "./globals.css";
import TheHeader from "../components/TheHeader";
import TheFooter from "@/components/TheFooter";

const font = Montagu_Slab({ subsets: ["latin"] });

export const metadata: Metadata = {
    title: "Create Next App",
    description: "Generated by create next app",
};

export default function RootLayout({
    children,
}: {
    children: React.ReactNode;
}) {
    return (
        <html lang="en">
            <body className={font.className}>
                <TheHeader />
                <main>{children}</main>
                <TheFooter />
            </body>
        </html>
    );
}
